### PR TITLE
Implement Subscribe to Cart

### LINKED ISSUE #15: Subscribe-to-cart functionality
All the infrastructure for this is already in place - the only task left seems to be the processing/saving of subscription schemes defined via **WooCommerce > Settings > Subscriptions**.

### PR DESCRIPTION
**Pull request by thenbrent**
To implement Subscribe to Cart, this PR:
* introduces `WCS_ATT_Admin::save_cart_level_settings()` which is responsible for saving schemes submitted when **WooCommerce > Settings > Subscriptions** is submitted
* introduces `WCS_ATT_Admin::save_schemes()` to provide a single function for saving schemes submitted via both **WooCommerce > Settings > Subscriptions** and **WooCommerce > Edit Product** admin screens for saving subscription schemes for both products and cart
* renames the `'subscription_schemes_metabox'` field type to be just `'subscription_schemes'` because there is no metabox on the **WooCommerce > Settings > Subscriptions** admin screen
* changes the option name to be `'wcsatt_subscribe_to_cart_schemes'` instead of `'woocommerce_subscriptions_subscribe_to_cart_schemes'`
* removes the _Enable Cart Subscription_ checkbox option as having no cart subscription schemes can be treated as disabling cart subscriptions

Screenshots:

1. Admin settings on first load (default scheme only available): https://cloudup.com/cw8aUSBKJ9O
1. Admin settings with schemes added: https://cloudup.com/cxVZsrBxPpu
1. cart page before selecting subscription scheme: https://cloudup.com/cVW3SLffLe1
1. cart page after selecting a subscription scheme: https://cloudup.com/cfbM2lCZlUA

This PR also introduces:

* removal of the mock product with SHA: 32c2833a03b4 for cart subscription price strings to use the v2.0 `wcs_price_string()` method instead (to work properly with single billing periods, this also needs https://github.com/Prospress/woocommerce-subscriptions/commit/1a219c44016a4f148f4f6a03ae91d91dc8b555d4 which will be merged to `master` soon)
* a small i18n fix with SHA: 9e4c01d
* a refactor of how scheme IDs are handled with SHA: ff23f01443, **this requires product level subscription schemes to be resaved to continue to work**. I've added this to the v1.1 milestone to help communicate this.
* a fix for undefined notices when `'woocommerce_tax_display_shop'` is not `false` with SHA: 563ef161ddf

Closes #15

### CODE REVIEW

**Comment by franticpsyx** [comment]
Awesome, thanks @thenbrent - it would be a pity not to have this in since the entire codebase was based on our initial spec that included this feature.

One Q before I review / merge:

>a refactor of how scheme IDs are handled [...] this requires product level subscription schemes to be resaved to continue to work

Is this for code readability? I haven't been able to pull download stats from the GitHub API to see how many people are using this, but is it worth the inconvenience the change will cause to existing users?

**Comment by franticpsyx** [comment]
@thenbrent Just noticed the merge conflicts - Any chance you can branch this out of `master`? I haven't made a release out of the `master` branch since I was hoping to look at https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/issues/20 before tagging a release, but other than that the `master` branch is stable worth releasing, even without https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/issues/20 solved.

**Comment by franticpsyx** [comment]
>Any chance you can branch this out of `master`? 

@thenbrent I'm taking this, might help us move things faster since you won't see this until tomorrow.

**Comment by franticpsyx** [comment]
@thenbrent Apologies for cherry-picking manually into https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/commit/b0b183007a4fdcc0a1e8c0d672c148b88b12362f - some parts of the code had changed significantly, so resolving the conflicts and merging would require some time.

**Comment by titocalabrese** [comment]
Hi, is there any hook that can be used in order to apply a discount to the cart in case the user decides to subscribe to the cart?

**Comment by thenbrent** [comment]
@titocalabrese you could use normal WooCommerce cart hooks (I don't know the best one off the top of my head, but you can search all the available hooks here: https://docs.woocommerce.com/wc-apidocs/hook-docs.html

The you can check if the cart contains subscriptions using `WC_Subscriptions_Cart::cart_contains_subscription()` (AFAIK I don't think there is a way to identify a cart converted to a single subscription vs. a cart that contains subscription products, but if you need that, we would accept a Pull Request to add it).

**Pull request closed without merging**
